Update 06-contexts.yaml

diff --git a/.github/workflows/06-contexts.yaml b/.github/workflows/06-contexts.yaml
--- a/.github/workflows/06-contexts.yaml
+++ b/.github/workflows/06-contexts.yaml
@@ -45,6 +45,11 @@ jobs:
           echo "Workflow env: ${{ env.MY_WORKFLOW_VAR }}"
           echo "Overwritten env: ${{ env.MY_OVERWRITTEN_VAR }}"
 
+      - name: Display Information
+        run: |
+          echo "Test"
+          exit 1  # <-- erzwingt failure
+
   echo-data2:
     runs-on: ubuntu-latest
     steps:
